### ISSUE TITLE
linux packages missing

### ISSUE THREAD

**Issue by kynan** [conda-forge/textblob-feedstock#2]
Seems the last [CircleCI build failed](https://circleci.com/gh/conda-forge/textblob-feedstock/4) so the linux-64 package is not available. Could you trigger another build please @pmlandwehr?

**Comment by kynan** [comment]
Any news on this @pmlandwehr?

**Comment by pmlandwehr** [comment]
Yep! I got super sidetracked. Regenerating and rebuilding the feedstock. Should hopefully be done soon.

**Comment by pmlandwehr** [comment]
Linux versions up!
